import { Palette, HorizontalBox } from "std-widgets.slint";

export component SidebarButton inherits Rectangle {
    in property <image> icon;
    in property <string> text;
    in property <bool> is-selected: false;
    callback clicked();
    
    border-radius: 8px;
    background: is-selected ? purple : touch.has-hover ? Palette.control-background : transparent;

    animate background {
        duration: 150ms;
    }

    VerticalLayout {
        alignment: center;
        horizontal-stretch: 1;
        spacing: 6px;
        height: parent.height;
        width: parent.width;
        padding-top: 10px;
        padding-bottom: 10px;
        
        VerticalLayout {
            HorizontalLayout {
                alignment: center;
                Image {
                    source: icon;
                    width: 22px;
                    height: 22px;
                    colorize: Palette.foreground;
                    horizontal-alignment: center;
                }
            }
        }

        Text {
            text: root.text;
            color: Palette.foreground;
            horizontal-alignment: center;
            font-size: 11px;
        }
    }

    touch := TouchArea {
        mouse-cursor: MouseCursor.pointer; 
        clicked => {
            root.clicked();
        }
    }
}