import {
    Palette,
    VerticalBox,
    Button,
    StandardListView,
} from "std-widgets.slint";

struct Song {
    title: string,
    plays: string,
}

component SongRow inherits Rectangle {
    in property <Song> song;
    in property <bool> selected: false;
    in property <int> ix: 0;

    callback play();

    //height: 60px;
    background: touch-area.has-hover ? Palette.control-background : transparent;

    touch-area := TouchArea {
        clicked => { root.play(); }
    }

    HorizontalLayout {
        spacing: 20px;
        padding-right: 60px;
        
        Text {
            text: ix;
            vertical-alignment: center;
            font-weight: 600;
            opacity: 0.6;
            font-size: 17px;
        }

        VerticalLayout {
            horizontal-stretch: 1;
            alignment: center;
            spacing: 4px;

            Text {
                text: song.title;
                font-weight: 600;
                font-size: 16px;
                horizontal-alignment: left;
            }

            Text {
                text: song.plays;
                font-weight: 300;
                font-size: 13px;
                color: Palette.foreground.with-alpha(0.6);
                horizontal-alignment: left;
            }
        }

        HorizontalLayout {
            alignment: end;
            spacing: 20px;
            height: 50px;

            Image {
                source: @image-url("../assets/icons/thumbs-up.svg");
                colorize: Palette.foreground;
            }

            Image {
                source: @image-url("../assets/icons/thumbs-down.svg");
                colorize: Palette.foreground;
            }

            Image {
                source: @image-url("../assets/icons/ellipsis-vertical.svg");
                colorize: Palette.foreground;
            }
        }
    }
}

export component AlbumView inherits VerticalLayout {
    width: 100%;
    height: 100%;
    alignment: start;
    padding-left: 40px;
    padding-right: 40px;
    padding-top: 40px;
    vertical-stretch: 1;

    in property <[Song]> songs: [
        { title: "五等分の気持ち - Gotoubun no Kimochi", plays: "11M plays" },
        { title: "ごぶんのいち - Gobun no Ichi", plays: "3M plays" },
        { title: "五等分の気持ち (TV EDIT) - Gotoubun no Kimochi (TV Edit)", plays: "11M plays" },
        { title: "五等分の気持ち (インストゥルメンタル) - Gotoubun no Kimochi (Instrumental)", plays: "83K plays" },
        { title: "ごぶんのいち (インストゥルメンタル) - Gobun no Ichi (Instrumental)", plays: "28K plays" },
    ];

    HorizontalLayout {
        spacing: 20px;

        Image {
            source: @image-url("../assets/cover_1.jpg");
            preferred-width: 250px;
            preferred-height: 250px;
            horizontal-alignment: ImageHorizontalAlignment.left;
        }

        VerticalLayout {
            horizontal-stretch: 1;
            alignment: start;
            spacing: 5px;
            Text {
                text: "Gotoubun no Kimochi";
                font-weight: 600;
                font-size: 35px;
                horizontal-alignment: start;
            }

            Text {
                text: "Nakanoke no Itsutsugo";
                font-weight: 400;
                font-size: 20px;
                horizontal-alignment: start;
            }

            Text {
                text: "EP • 2019";
                font-weight: 300;
                font-size: 15px;
                horizontal-alignment: start;
            }

            Text {
                text: "5 songs • 18 minutes";
                font-weight: 300;
                font-size: 15px;
                horizontal-alignment: start;
            }

            Rectangle {
                height: 20px;
            }

            HorizontalLayout {
                alignment: start;
                spacing: 10px;

                Button {
                    text: "Play";
                    icon: @image-url("../assets/icons/play.svg");
                    colorize-icon: true;
                    primary: true;
                }

                Button {
                    text: "Save";
                    icon: @image-url("../assets/icons/bookmark.svg");
                    colorize-icon: true;
                }

                Button {
                    text: "Share";
                    icon: @image-url("../assets/icons/share.svg");
                    colorize-icon: true;
                }

                Button {
                    icon: @image-url("../assets/icons/ellipsis-vertical.svg");
                    colorize-icon: true;
                }
            }
        }
    }

    Rectangle {
        height: 40px;
    }

    VerticalLayout {
        spacing: 10px; 
        for song[index] in root.songs: SongRow {
            song: song;
            ix: index + 1;
        }
    }
}
