import { VerticalBox, Button } from "std-widgets.slint";
import { RootView } from "root-view.slint";


export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();

    preferred-width: 1280px;
    preferred-height: 720px;
    title: "Philharmonica";

    RootView {
        width: 100%;
        x: 0px;
        y: 1px;
        height: 100%;
    }
}

