import { Palette, VerticalBox, Button, AboutSlint } from "std-widgets.slint";
import { SidebarButton } from "components/sidebar-button.slint";
import { AlbumView } from "album-page.slint";
import { Player } from "components/player.slint";

struct MenuItems { name: string, icon: image}

export component RootView inherits Rectangle {
    in-out property <int> selected-index: 0;
    in property <[MenuItems]> menu-items: [
        { name: "Home", icon: @image-url("../assets/icons/house.svg") },
        { name: "Search", icon: @image-url("../assets/icons/search.svg") },
        { name: "Explore", icon: @image-url("../assets/icons/compass.svg") },
        { name: "Library", icon: @image-url("../assets/icons/bookmark.svg") },
        { name: "Settings", icon: @image-url("../assets/icons/settings.svg") }
    ];

    HorizontalLayout {
        Rectangle {
            width: 70px;
            background: Palette.control-background;

            VerticalBox {
                spacing: 10px;
                height: 100%;
                alignment: start;

                SidebarButton {
                    icon: @image-url("../assets/icons/arrow-left.svg");
                    text: "Back";
                }

                for data[index] in root.menu-items: SidebarButton {
                    icon: data.icon;
                    text: data.name;
                    is-selected: selected-index == index;
                    clicked => {
                        selected-index = index;
                    }
                }
            }
        }

        AlbumView { 
        }
    }

    Player {
        z: 1;
        y: parent.height - 70px;
    }
}
